# Generated by Django 4.2.1 on 2023-08-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms_posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyInterest",
            fields=[
                ("interest_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "muser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms_posts.rooms",
                    ),
                ),
            ],
            options={
                "db_table": "my_interest",
                "managed": True,
            },
        ),
    ]
