# Generated by Django 4.2.1 on 2023-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("student_num", models.IntegerField()),
                ("email", models.EmailField(max_length=45, unique=True)),
                ("password", models.CharField(max_length=45)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True, null=True)),
                ("phone", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
    ]
