# Generated by Django 4.2.1 on 2023-08-24 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                ("rooms_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=100)),
                ("area", models.IntegerField()),
                ("deposit", models.IntegerField(blank=True, null=True)),
                ("monthly_rent", models.IntegerField(blank=True, null=True)),
                ("maintenance_cost", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("structure", models.CharField(max_length=3)),
                ("women_only", models.IntegerField()),
                ("location", models.CharField(blank=True, max_length=5, null=True)),
                ("sold", models.IntegerField()),
                ("category", models.CharField(max_length=5)),
                ("title", models.CharField(max_length=30)),
                ("comment", models.TextField()),
                ("interest", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "ruser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "managed": True,
            },
        ),
    ]
